--delete from processed_file;
--delete from transaction;
-- delete from expense;
-- delete from tax;
-- delete from investment;
-- select count(1) from processed_file;
select 1 from dual;


-- Autogenerated: do not edit this file